export const CurationDatabaseV1Abi = [
    {
      inputs: [
        { internalType: 'address', name: '_initialOwner', type: 'address' },
        {
          internalType: 'address',
          name: '_initialSecondaryOwner',
          type: 'address',
        },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    {
      inputs: [
        { internalType: 'uint256', name: '_size', type: 'uint256' },
        { internalType: 'uint256', name: '_start', type: 'uint256' },
        { internalType: 'uint256', name: '_end', type: 'uint256' },
      ],
      name: 'InvalidCodeAtRange',
      type: 'error',
    },
    { inputs: [], name: 'Invalid_Input_Length', type: 'error' },
    { inputs: [], name: 'NOT_EITHER_OWNER', type: 'error' },
    { inputs: [], name: 'No_Initialize_Access', type: 'error' },
    { inputs: [], name: 'No_Settings_Access', type: 'error' },
    { inputs: [], name: 'No_Sort_Access', type: 'error' },
    { inputs: [], name: 'ONLY_OWNER', type: 'error' },
    { inputs: [], name: 'ONLY_PENDING_OWNER', type: 'error' },
    { inputs: [], name: 'OWNER_CANNOT_BE_ZERO_ADDRESS', type: 'error' },
    { inputs: [], name: 'Press_Not_Initialized', type: 'error' },
    { inputs: [], name: 'WriteError', type: 'error' },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'targetPress',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'overwriteCaller',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'tokenId',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'address',
          name: 'newPointer',
          type: 'address',
        },
      ],
      name: 'DataOverwritten',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'targetPress',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'removeCaller',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'tokenId',
          type: 'uint256',
        },
      ],
      name: 'DataRemoved',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'targetPress',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'sortCaller',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256[]',
          name: 'ids',
          type: 'uint256[]',
        },
        {
          indexed: false,
          internalType: 'int128[]',
          name: 'sortOrders',
          type: 'int128[]',
        },
      ],
      name: 'DataSorted',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'targetPress',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'storeCaller',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'tokenId',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'address',
          name: 'pointer',
          type: 'address',
        },
      ],
      name: 'DataStored',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'targetPress',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'logic',
          type: 'address',
        },
      ],
      name: 'LogicUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'sender',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'factory',
          type: 'address',
        },
      ],
      name: 'NewFactoryAdded',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'owner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'canceledOwner',
          type: 'address',
        },
      ],
      name: 'OwnerCanceled',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'owner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'pendingOwner',
          type: 'address',
        },
      ],
      name: 'OwnerPending',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'prevOwner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newOwner',
          type: 'address',
        },
      ],
      name: 'OwnerUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'sender',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'targetPress',
          type: 'address',
        },
      ],
      name: 'PressInitialized',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'targetPress',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'renderer',
          type: 'address',
        },
      ],
      name: 'RendererUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'prevSecondaryOwner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newSecondaryOwner',
          type: 'address',
        },
      ],
      name: 'SecondaryOwnerUpdated',
      type: 'event',
    },
    {
      inputs: [],
      name: 'acceptOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'burnCaller', type: 'address' },
        { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      ],
      name: 'canBurn',
      outputs: [{ internalType: 'bool', name: 'burnAccess', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'dataCaller', type: 'address' },
      ],
      name: 'canEditContractData',
      outputs: [{ internalType: 'bool', name: 'contractAccess', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'paymentsCaller', type: 'address' },
      ],
      name: 'canEditPayments',
      outputs: [{ internalType: 'bool', name: 'paymentsAccess', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'settingsCaller', type: 'address' },
      ],
      name: 'canEditSettings',
      outputs: [{ internalType: 'bool', name: 'settingsAccess', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'dataCaller', type: 'address' },
        { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      ],
      name: 'canEditTokenData',
      outputs: [{ internalType: 'bool', name: 'tokenAccess', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'mintCaller', type: 'address' },
        { internalType: 'uint256', name: 'mintQuantity', type: 'uint256' },
      ],
      name: 'canMint',
      outputs: [{ internalType: 'bool', name: 'mintAccess', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'sortCaller', type: 'address' },
      ],
      name: 'canSort',
      outputs: [{ internalType: 'bool', name: 'sortAccess', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'cancelOwnershipTransfer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'contractURI',
      outputs: [{ internalType: 'string', name: 'uri', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'targetPress', type: 'address' }],
      name: 'getAllSortData',
      outputs: [
        { internalType: 'int128[]', name: 'sortOrders', type: 'int128[]' },
      ],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      name: 'idToData',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'targetPress', type: 'address' }],
      name: 'initializePress',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bytes', name: 'databaseInit', type: 'bytes' }],
      name: 'initializeWithData',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'targetPress', type: 'address' }],
      name: 'isInitialized',
      outputs: [{ internalType: 'bool', name: 'initialized', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
      name: 'isOfficialFactory',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'overwriteCaller', type: 'address' },
        { internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
        { internalType: 'bytes[]', name: 'newData', type: 'bytes[]' },
      ],
      name: 'overwriteData',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'owner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'pendingOwner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'targetPress', type: 'address' }],
      name: 'readAllData',
      outputs: [{ internalType: 'bytes[]', name: 'activeData', type: 'bytes[]' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      ],
      name: 'readData',
      outputs: [{ internalType: 'bytes', name: 'data', type: 'bytes' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'removeCaller', type: 'address' },
        { internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
      ],
      name: 'removeData',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'resignOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'resignSecondaryOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
      name: 'safeTransferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'secondaryOwner',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'logic', type: 'address' },
        { internalType: 'bytes', name: 'logicInit', type: 'bytes' },
      ],
      name: 'setLogic',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'factory', type: 'address' }],
      name: 'setOfficialFactory',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'renderer', type: 'address' },
        { internalType: 'bytes', name: 'rendererInit', type: 'bytes' },
      ],
      name: 'setRenderer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'settingsInfo',
      outputs: [
        { internalType: 'uint256', name: 'storedCounter', type: 'uint256' },
        { internalType: 'address', name: 'logic', type: 'address' },
        { internalType: 'uint8', name: 'initialized', type: 'uint8' },
        { internalType: 'address', name: 'renderer', type: 'address' },
      ],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      name: 'slotToSort',
      outputs: [{ internalType: 'int128', name: '', type: 'int128' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
        { internalType: 'int128[]', name: 'sortOrders', type: 'int128[]' },
      ],
      name: 'sortData',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'storeCaller', type: 'address' },
        { internalType: 'bytes', name: 'data', type: 'bytes' },
      ],
      name: 'storeData',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'tokenURI',
      outputs: [{ internalType: 'string', name: 'uri', type: 'string' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'targetPress', type: 'address' },
        { internalType: 'address', name: 'mintCaller', type: 'address' },
        { internalType: 'uint256', name: 'mintQuantity', type: 'uint256' },
      ],
      name: 'totalMintPrice',
      outputs: [{ internalType: 'uint256', name: 'price', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '_newSecondaryOwner', type: 'address' },
      ],
      name: 'transferSecondaryOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
  ] as const;